# Generated by Django 4.2.17 on 2025-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="services/", verbose_name="Картинка"
            ),
        ),
    ]
