# Generated by Django 4.2.17 on 2025-01-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="doctors/photo",
                verbose_name="Картинка",
            ),
        ),
    ]
